### ISSUE TITLE
TacticalLeaning not working - no HtK installed

### ISSUE THREAD

**Issue by Dushess** [offyerrocker/HoldTheKey#2]
![image](https://user-images.githubusercontent.com/15954961/95613493-b6d41f00-0a6d-11eb-82e2-74f9c4adc978.png)
See, HtK is not installed.
Funny thing - all fine with WolfHud.

**Comment by offyerrocker** [comment]
Which version of Tactical Lean do you have, and which version of Hold The Key do you have? Have you made sure that both mods are up-to-date from ModWorkshop?

**Comment by Dushess** [comment]
HTK is latest from MWS, TL has been updeted ingame, (it's working there) so it also should be latest. mod.txt says 2.02

**Comment by Dushess** [comment]
Wait, oh sh~
